DROP  TABLE PAYMENTS_INFO CASCADE CONSTRAINTS;
DROP TABLE BOOKINGS CASCADE CONSTRAINTS;
DROP TABLE SERVICES CASCADE CONSTRAINTS;
DROP TABLE TOURISM CASCADE CONSTRAINTS;
DROP TABLE CHECK_INFORMATION CASCADE CONSTRAINTS;
DROP TABLE HOTEL_INFO CASCADE CONSTRAINTS;
DROP TABLE BILLING CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE ROOM_INFORMATION CASCADE CONSTRAINTS;
DROP TABLE EMPLOYE CASCADE CONSTRAINTS;




